import 'dart:developer';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'network_exceptions.freezed.dart';

@freezed
abstract class NetworkExceptions with _$NetworkExceptions {
  const factory NetworkExceptions.requestCancelled() = RequestCancelled;

  const factory NetworkExceptions.unauthorisedRequest() = UnauthorisedRequest;

  const factory NetworkExceptions.badRequest() = BadRequest;

  const factory NetworkExceptions.notFound(String reason) = NotFound;

  const factory NetworkExceptions.methodNotAllowed() = MethodNotAllowed;

  const factory NetworkExceptions.notAcceptable() = NotAcceptable;

  const factory NetworkExceptions.requestTimeout() = RequestTimeout;

  const factory NetworkExceptions.sendTimeout() = SendTimeout;

  const factory NetworkExceptions.conflict() = Conflict;

  const factory NetworkExceptions.internalServerError() = InternalServerError;

  const factory NetworkExceptions.notImplemented() = NotImplemented;

  const factory NetworkExceptions.serviceUnavailable() = ServiceUnavailable;

  const factory NetworkExceptions.noInternetConnection() = NoInternetConnection;

  const factory NetworkExceptions.formatException() = FormatException;

  const factory NetworkExceptions.unableToProcess(String error,
      {StackTrace? stackTrace}) = UnableToProcess;

  const factory NetworkExceptions.defaultError(String error) = DefaultError;

  const factory NetworkExceptions.unexpectedError() = UnexpectedError;

  static NetworkExceptions getDioException(error, StackTrace? stackTrace) {
    if (error is Exception) {
      try {
        NetworkExceptions networkExceptions = const NetworkExceptions.unexpectedError();
        if (error is DioException) {
          log(error.toString());
          switch (error.type) {
            case DioExceptionType.cancel:
              networkExceptions = const NetworkExceptions.requestCancelled();
              break;
            case DioExceptionType.connectionTimeout:
              networkExceptions = const NetworkExceptions.requestTimeout();
              break;
            //todo check  is internet connection working correctly
            case DioExceptionType.unknown:
              networkExceptions = const NetworkExceptions.noInternetConnection();
              break;
            case DioExceptionType.receiveTimeout:
              networkExceptions = const NetworkExceptions.requestTimeout();
              break;
            // case DioErrorType.response:
            //   switch (error.response?.statusCode) {
            //     case 400:
            //       networkExceptions =
            //       const NetworkExceptions.unauthorisedRequest();
            //       break;
            //     case 401:
            //       networkExceptions =
            //       const NetworkExceptions.unauthorisedRequest();
            //       break;
            //     case 403:
            //       networkExceptions =
            //       const NetworkExceptions.unauthorisedRequest();
            //       break;
            //     case 404:
            //       //Todo move to dic
            //       networkExceptions =
            //       const NetworkExceptions.notFound("Not found");
            //       break;
            //     case 409:
            //       networkExceptions = const NetworkExceptions.conflict();
            //       break;
            //     case 408:
            //       networkExceptions = const NetworkExceptions.requestTimeout();
            //       break;
            //     case 500:
            //       networkExceptions =
            //       const NetworkExceptions.internalServerError();
            //       break;
            //     case 503:
            //       networkExceptions =
            //       const NetworkExceptions.serviceUnavailable();
            //       break;
            //     default:
            //       var responseCode = error.response?.statusCode;
            //       networkExceptions = NetworkExceptions.defaultError(
            //         // "Received invalid status code: $responseCode",
            //         " خطای عدم دسترسی به اینترنت" + " و یا فعال بودن " + "VPN",
            //       );
            //   }
            //   break;
            case DioExceptionType.sendTimeout:
              networkExceptions = const NetworkExceptions.sendTimeout();
              break;
            default:
              networkExceptions = const NetworkExceptions.unexpectedError();
          }
        } else if (error is SocketException) {
          networkExceptions = const NetworkExceptions.noInternetConnection();
        } else {
          networkExceptions = const NetworkExceptions.unexpectedError();
        }
        return networkExceptions;
      } on FormatException catch (_) {
        // Helper.printError(e.toString());
        return const NetworkExceptions.formatException();
      } catch (_) {
        return const NetworkExceptions.unexpectedError();
      }
    } else {
      if (error.toString().contains("is not a subtype of")) {
        return NetworkExceptions.unableToProcess(
            error.toString() , stackTrace: stackTrace);
      } else {
        return const NetworkExceptions.unexpectedError();
      }
    }
  }

  static String getErrorMessage(NetworkExceptions networkExceptions) {
    //TODO handel error server msg
    var errorMessage = "";
    networkExceptions.when(notImplemented: () {
      errorMessage = "Not Implemented";
    }, requestCancelled: () {
      errorMessage = "Request Cancelled";
    }, internalServerError: () {
      errorMessage = "Internal Server Error";
    }, notFound: (String reason) {
      errorMessage = reason;
    }, serviceUnavailable: () {
      errorMessage = "Service unavailable";
    }, methodNotAllowed: () {
      errorMessage = "Method Allowed";
    }, badRequest: () {
      errorMessage = "Bad request";
    }, unauthorisedRequest: () {
      errorMessage = "خطای دسترسی";
    }, unexpectedError: () {
      errorMessage = "خطای غیرمنتظره";
    }, requestTimeout: () {
      errorMessage = "پاسخی از سرور دریافت نشد، دوباره تلاش نمائید";
    }, noInternetConnection: () {
      errorMessage = "خطای عدم دسترسی به اینترنت، از دسترسی به اینترنت مطمئن شوید و دوباره تلاش نمائید";
    }, conflict: () {
      errorMessage = "Error due to a conflict";
    }, sendTimeout: () {
      errorMessage = " خطای عدم دسترسی به اینترنت و یا فعال بودن VPN";
    }, unableToProcess: (e, stacktrace) {
      log(stacktrace.toString());
      errorMessage = "پردازش اطلاعات امکانپذیر نیست";
    }, defaultError: (String error) {
      errorMessage = error;
    }, formatException: () {
      errorMessage = "Unexpected error occurred";
    }, notAcceptable: () {
      errorMessage = "Not acceptable";
    });
    return errorMessage;
  }
}
